linterとか
apcc/agc-game-2020 pull request #7
Opened 2020-10-12 12:40 UTC by ibuki2003

closes #6
- editorconfig
- clang-format

ルールはゴリゴリに自分好みに調整したので気に喰わなければ言ってくださいな
あとはgithub actionsをどうするか エラー吐いて落ちる他自動でなおしてpushしてくれるようにすることもできるみたい

2020-10-20 13:27 UTC, su8ru commented on src/Main.cpp
>  ﻿
この先頭の改行はいいの？

2020-10-20 13:29 UTC, ibuki2003 commented on src/Main.cpp
>  ﻿
2連改行を禁止しているだけなので、怒られないみたいですね 消す?

2020-10-20 13:29 UTC, su8ru commented on src/Main.cpp
>  ﻿
消そ～～～

2020-10-20 13:30 UTC, su8ru requested changes

2020-10-20 13:30 UTC, su8ru commented on src/Main.cpp
>  ﻿
```suggestion
```

2020-10-20 13:32 UTC, su8ru approved these changes
from github cli﻿

2020-10-21 07:11 UTC, Takeno-hito approved these changes

2020-10-21 07:43 UTC, merged