Sceneをたくさん追加した
apcc/agc-game-2020 pull request #9
Opened 2020-10-21 08:23 UTC by Takeno-hito

2020-10-21 11:45 UTC, su8ru requested changes
eof に new line がないので、rebase なりなんなりして lint かけてください

2020-10-22 07:08 UTC, ibuki2003 requested changes
子シーンはクラスなのですか?(いいえ)
Gameシーンクラスのメンバなので宣言はclass内、定義を.cppに書いてください: hpp ファイルを消してください

2020-10-23 02:50 UTC, su8ru submitted a review, later dismissed

2020-10-23 03:38 UTC, ibuki2003 approved these changes

2023-06-03 13:07 UTC, closed without merging